### ISSUE TITLE
Scripts for Self-Play, Console-IO Play, and 2D Connect2

### ISSUE THREAD

**Issue by tslever** [JoshVarty/AlphaZeroSimple#3]
Mr. Varty,

Would be willing to provide scripts or ideas for self-play, console-IO play, and/or 2D games?

Tom Lever

**Comment by JoshVarty** [comment]
To be honest I will probably not be able to add any of these requests. My project is meant to be a "toy" and an example of MCTS in the simplest possible environment. Adding more features would make it harder for me to keep things as simple as possible.

That said there are a few great projects out there that do exactly what you're looking for:

- [Alpha Zero General](https://github.com/suragnair/alpha-zero-general) has support for a number of 2D games and allows you to add your own games as well.
- [MuZero General](https://github.com/werner-duvaud/muzero-general/) implements the MuZero algorithm and has great documentation and is one of the best projects I've seen in this area.

Hopefully these will give you the full feature set you're looking for!
